/*
 * File: app/view/OrgCfgWin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('platform.system.view.OrgCfgWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.OrgCfgWin',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 245,
    width: 500,
    title: '系统配置编辑',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    height: 348,
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '配置项名称',
                            labelAlign: 'right',
                            name: 'name',
                            emptyText: '请输入菜单名称',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '配置项值',
                            labelAlign: 'right',
                            name: 'value'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '上级配置项值',
                            labelAlign: 'right',
                            name: 'valueParent',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '备注',
                            labelAlign: 'right',
                            name: 'memo'
                        },
                        {
                            xtype: 'radiogroup',
                            hidden: true,
                            fieldLabel: '允许下级组织更改',
                            labelAlign: 'right',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'subOrgUpdate',
                                    boxLabel: '是',
                                    inputValue: 'true'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'subOrgUpdate',
                                    boxLabel: '否',
                                    checked: true,
                                    inputValue: 'false'
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: '排列顺序',
                            labelAlign: 'right',
                            name: 'sort',
                            value: 1,
                            minValue: 0
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onFormAfterRender,
                            scope: me
                        }
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    defaultAlign: 'right',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-ok',
                            text: '确 定',
                            listeners: {
                                click: {
                                    fn: me.onBtnOkClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-cancel',
                            text: '取 消',
                            listeners: {
                                click: {
                                    fn: me.onBtnCancelClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onFormAfterRender: function(component, eOpts) {
            this.form = component;
    },

    onBtnOkClick: function(button, e, eOpts) {
        var me = this;
        try{
            Common.formSubmit({
                url : ctxp+'/system/OrgCfgController/save',
                form:me.form,
                callback : function(result)
                {
                	me.close();
            	}
        	});
        }catch(error){
            Common.show({title:'信息提示',html:error.toString()});
        }
    },

    onBtnCancelClick: function(button, e, eOpts) {
        this.close();
    },

    loadForm: function(id) {
            var me = this;
                try{
                    Common.ajax({
                        component : me.form,
                        message : '加载信息...',
                        url : ctxp+'/system/OrgCfgController/load?id='+id,
                        callback : function(result)
                        {
                            me.form.getForm().reset();
                            var subOrgUpdate = result.rows.subOrgUpdate;
        							if(subOrgUpdate){
        								result.rows.subOrgUpdate = 'true';
        							}else{
        								result.rows.subOrgUpdate = 'false';
        							}
                            me.form.getForm().setValues(result.rows);
                        }
                    });
                }
                catch(error)
                {
                    Common.show({title:'信息提示',html:error.toString()});
                }
    }

});