/*
 * File: app/view/UserDetailWin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('platform.system.view.UserDetailWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.UserDetailWin',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea'
    ],

    height: 437,
    width: 432,
    resizable: false,
    layout: 'border',
    title: '编辑用户信息',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-save',
                            text: '保存',
                            listeners: {
                                click: {
                                    fn: me.onsaveClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-cancel',
                            text: '取消',
                            listeners: {
                                click: {
                                    fn: me.onCancelClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    border: false,
                    autoScroll: true,
                    layout: 'column',
                    bodyPadding: 10,
                    header: false,
                    title: '基本信息表单',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '登录帐号',
                            labelAlign: 'right',
                            name: 'username',
                            fieldCls: '',
                            allowBlank: false,
                            enforceMaxLength: true,
                            maxLength: 20
                        },
                        {
                            xtype: 'label',
                            html: '<font color=red>*</font>',
                            padding: '10 5 5 5'
                        },
                        {
                            xtype: 'textfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '用户姓名',
                            labelAlign: 'right',
                            name: 'name',
                            allowBlank: false,
                            enforceMaxLength: true,
                            maxLength: 50
                        },
                        {
                            xtype: 'label',
                            html: '<font color=red>*</font>',
                            padding: '10 5 5 5'
                        },
                        {
                            xtype: 'textfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '手机号码',
                            labelAlign: 'right',
                            name: 'mobile',
                            allowBlank: false,
                            enforceMaxLength: true,
                            maxLength: 20
                        },
                        {
                            xtype: 'label',
                            html: '<font color=red>*</font>',
                            padding: '10 5 5 5'
                        },
                        {
                            xtype: 'textfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '所属机构',
                            labelAlign: 'right',
                            name: 'orgName',
                            readOnly: true,
                            allowBlank: false,
                            enforceMaxLength: true,
                            maxLength: 50,
                            listeners: {
                                focus: {
                                    fn: me.onOrgTextfieldFocus,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'label',
                            html: '<font color=red>*</font>',
                            padding: '10 5 5 5'
                        },
                        {
                            xtype: 'hiddenfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '所属机构',
                            labelAlign: 'right',
                            name: 'orgId'
                        },
                        {
                            xtype: 'textfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '岗位名称',
                            labelAlign: 'right',
                            name: 'jobName',
                            enforceMaxLength: true,
                            maxLength: 50
                        },
                        {
                            xtype: 'combobox',
                            padding: 5,
                            width: 330,
                            fieldLabel: '用户性别',
                            labelAlign: 'right',
                            name: 'sex',
                            editable: false,
                            displayField: 'userSex',
                            valueField: 'id',
                            listeners: {
                                afterrender: {
                                    fn: me.onSexAfterRender,
                                    scope: me
                                },
                                beforerender: {
                                    fn: me.onSexBeforeRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            padding: 5,
                            width: 330,
                            fieldLabel: '认证方式',
                            labelAlign: 'right',
                            name: 'authType',
                            editable: false,
                            valueField: 'id',
                            listeners: {
                                beforerender: {
                                    fn: me.onAuthTypeBeforeRender,
                                    single: true,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '身份证号码',
                            labelAlign: 'right',
                            name: 'idCard',
                            enforceMaxLength: true,
                            maxLength: 50
                        },
                        {
                            xtype: 'textareafield',
                            padding: 5,
                            width: 330,
                            fieldLabel: '备注',
                            labelAlign: 'right',
                            name: 'memo',
                            enforceMaxLength: true,
                            maxLength: 256,
                            maxLengthText: '备注内容最大长度不超过256个字符！'
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onFormAfterRender,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onsaveClick: function(button, e, eOpts) {
        var me = this;
        try{
            Common.formSubmit({
                url : ctxp+'/system/user/saveUser',
                form:me.form,
                callback : function(result)
                {
                    Ext.Msg.alert('信息提示', '用户保存成功！');
                	me.close();
            	}
        	});
        }catch(error){
            Common.show({title:'信息提示',html:error.toString()});
        }
    },

    onCancelClick: function(button, e, eOpts) {
        var me=this;
        me.close();
    },

    onOrgTextfieldFocus: function(component, e, eOpts) {
        try{
            var me = this;
            var orgId = me.form.getForm().findField('orgId');
            Common.showTreeSelect({
                multiple:false,
                url:ctxp + '/home/loadUserOrgTree?orgId=' + orgId.getValue(),
                callback:function(item)
                {
                    orgId.setValue(item.id);
                    component.setValue(item.text);
                }
            });
        }catch(ex){}
    },

    onSexAfterRender: function(component, eOpts) {
        var store = Ext.create('Ext.data.Store', {
            fields:['id','userSex'],
            data : [{id:'',userSex: ''},{id:'0',userSex: '男'}, {id:'1',userSex: '女'}]
        });
        component.bindStore(store);
    },

    onSexBeforeRender: function(component, eOpts) {
        this.userSex = component;
    },

    onAuthTypeBeforeRender: function(component, eOpts) {
        try{
            var me = this;
            Common.loadStore({
                component:component,
                url:ctxp + '/home/authType',
                fields:['id','text'],
                params:[]
            });
        }
        catch(e){
            Common.show(e.toString());
        }
    },

    onFormAfterRender: function(component, eOpts) {
        this.form = component;


    },

    loadForm: function(id) {

        var me = this;
        try{
            Common.ajax({
                params:{'id':id},
                component : me.form,
                message : '加载信息...',
                url : ctxp+'/system/user/loadById',
                callback : function(result)
                {
                    me.form.getForm().reset();
                    me.form.getForm().setValues(result.rows);
                    if(!Ext.isEmpty(id)){

                        me.form.getForm().findField('username').setReadOnly(true);

                    }
                }
            });
        }
        catch(error)
        {
            Common.show({title:'信息提示',html:error.toString()});
        }
    }

});