/*
 * File: app/view/UserSelect.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('platform.system.view.UserSelect', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.UserSelect',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel'
    ],

    height: 250,
    width: 400,
    title: '',
    forceFit: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'name',
                    text: '姓名'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'orgName',
                    text: '组织名称'
                }
            ],
            selModel: Ext.create('Ext.selection.CheckboxModel', {
                mode: 'SINGLE'
            })
        });

        me.callParent(arguments);
    },

    loadData: function(username) {

        var me = this;
        Common.ajax({
            component : me,
            params:{'username':username},
            message : '正在加载......',
            url : ctxp+'/manage/authority/findUserByName',
            callback : function(result)
            {
                var UserStore = Ext.create('Ext.data.Store', {
                    storeId:'UserStore',
                    fields: ['id','name','orgName'],
                    data : result.rows,
                    proxy:
                    {
                        type: 'memory',
                        reader:{
                            type: 'json'
                        }
                    },
        					listeners:{
        						load:{
        							fn:function(gridStore, records, successful, eOpts){

        								if(me.toUserId){
        									for(var i=0;i<gridStore.getCount();i++){
        										var record = gridStore.getAt(i);
        										if(record.data.id ===me.toUserId){
        											me.getSelectionModel().select(record);
        										}
        									}
        								}

        							}
        						}
        					}
                });
                me.bindStore(UserStore);
            }
        });

    }

});